### ISSUE TITLE
problems with examples

### ISSUE THREAD

**Issue by davidalanreid** [ssc-oscar/oscar.py#24]
I want to get the heads of a project and traverse the tree.
I was not able to get it to work. I backed up and just tried
getting some of the examples to work and had some trouble. I
don't know if I'm doing something wrong or if there is a problem
with oscar.py.

I tried this example from from https://ssc-oscar.github.io/oscar.py/
    >>> tree = Tree("d4ddbae978c9ec2dc3b7b3497c2086ecf7be7d9d")
    >>> '.gitignore' in tree
    True
when I run it it returns False instead of True. (using ~/lookup/showCnt tree,
I can see that it should return True as shown in the example.)

This example is in the comments in oscar.py
    c = Commit('e38126dbca6572912013621d2aa9e6f7c50f36bc')
    print c.authored_at
when I run it, I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "oscar.py", line 832, in __getattr__
    self.header, self.full_message = self.data.split("\n\n", 1)
ValueError: need more than 1 value to unpack

 (again, ~/lookup agrees with what the documentation says it should return).

**Comment by px1624** [comment]
Commit and Tree data files are located on da4, try ssh into da4 first and see if that solves the problem.

**Comment by user2589** [comment]
Both commit and tree data is empty. @audrism it seems like a regression between versions

**Comment by user2589** [comment]
False alarm, I was using an outdated version. Tried this on da4 and it works

**Comment by davidalanreid** [comment]
Yes, that solved it, running a da4 works. Thanks.
