### ISSUE TITLE
No keys found for path_template

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/oscar.py#28]
I'm running oscar.py on da4 and get this warning when importing `Author` from oscar

What I did on terminal:
```
Python 2.7.5 (default, Apr  2 2020, 13:16:51) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from oscar import Author
oscar.py:63: UserWarning: No keys found for path_template /fast/All.sha1/sha1.blob_{key}.tch
  warnings.warn("No keys found for path_template " + path_template)
oscar.py:63: UserWarning: No keys found for path_template /fast/All.sha1/sha1.tree_{key}.tch
  warnings.warn("No keys found for path_template " + path_template)
oscar.py:63: UserWarning: No keys found for path_template /fast/All.sha1o/sha1.commit_{key}.tch
  warnings.warn("No keys found for path_template " + path_template)
oscar.py:63: UserWarning: No keys found for path_template /fast/All.sha1o/sha1.tree_{key}.tch
  warnings.warn("No keys found for path_template " + path_template)
```

How can this warning be prevented?

**Comment by k----n** [comment]
Is it because the default key has to be set here?

https://github.com/ssc-oscar/oscar.py/blob/5a44c0b3ba7aaf6b648198ab3c1897c1623b954d/oscar.py#L107-L168

The default paths are different from the tutorial: https://github.com/woc-hack/tutorial/blob/master/README.md#environment-variable-configuration-for-oscar

**Comment by user2589** [comment]
These files are indeed missing, but they aren't used by the package. At this point the easiest workaround is to ignore the warnings, in the next version we'll remove these paths.

@audris Can you confirm these files are no longer maintained?

**Comment by audrism** [comment]
I commented out the offending paths in the latest commit. 

The basic issue concerns which hosts have what paths:

1. /fast/All.sha1 is only needed for discovery: commented out
2. /fast/All.sha1o/{commit/tree} are needed on da3 that has not enough space on ssd raid to have 
/fast/All.sha1c/{commit/tree}
