### ISSUE TITLE
No Commit SHAs found For Author

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/oscar.py#30]
I am using the the master branch of this repo.

```
>>> from oscar import Author
>>> Author('"Albert Krawczyk" <pro-logic@optusnet.com.au>').commit_shas
()
>>> Author('Audris Mockus <audris@utk.edu>').commit_shas
()
```

**Comment by audrism** [comment]
The update to ver S is ongoing now. You can manually set environment to use S and R if S is not available. The default code uses R

**Comment by audrism** [comment]
The update to ver S is ongoing now. You can manually set environment to use S and R if S is not available. The default code uses R

**Comment by audrism** [comment]
I have create symlinks on da0 that for maps that do not have S link back to R

**Comment by audrism** [comment]
@k----n Seems to work now close?
