### ISSUE TITLE
Missing Functions Mentioned in Tutorial

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/oscar.py#31]
For example I can't find any toURL method in oscar.py: https://github.com/woc-hack/tutorial/blob/master/README.md#exercise-4b-get-the-url-of-a-projects-repository-using-the-oscarpy-projecttourl-function

As well, the Project class does not have a fork_commits seen here: https://github.com/woc-hack/tutorial/blob/master/README.md#activity-4-using-python-apis-from-oscarpy

**Comment by audrism** [comment]
Thank you!

1. I fixed the tutorial to use url attribute instead of toURL function

2. I dropped fork_commits reference


To actually get all commits in all forks, use 

1) p2P

2) use P2c for all P's obtained in step1
