### ISSUE TITLE
An issue about Project class's toURL method

### ISSUE THREAD

**Issue by KayGau** [ssc-oscar/oscar.py#5]
https://github.com/ssc-oscar/oscar.py/blob/359b9a080aa4aa6944dbb8bc99bd798e58d139fc/oscar.py#L1243
```
p_name = p_name.replace('_', '/')
```
I think it will replace all '_' (including those in repo name) with '/'
I think it should be 
```
p_name = p_name.replace('_', '/',1)
```
to replace only the first one

**Comment by audrism** [comment]
Please fix
