### ISSUE TITLE
Problems with import oscar

### ISSUE THREAD

**Issue by zifeiyu87** [ssc-oscar/oscar.py#55]
I connected da4, da4 has pre installed oscar v2.2.1, but I am unable to import oscar in Python 3. The error message is as follows:
<img width="669" alt="image" src="https://github.com/ssc-oscar/oscar.py/assets/59904370/7a79b1a1-eda3-4405-934a-69d109edef70">
I have tried v2.2.1, v2.2.0, v2.1.0, and I have also run the command in Tutorial: "easy_ Install -- user clickhouse driver".
I also tried to build and install oscar [as per the installation instructions in Oscar. py](https://github.com/ssc-oscar/oscar.py#installation), using "python3 setup.py build_ext && python3 setup.py install --user"
But none of these works, I still cannot import Oscar correctly.

**Comment by user2589** [comment]
The package was not updated in a while, and it looks like some mappings are now stored under different paths or using a different name convention. I'll try to look into this the upcoming weekend

**Comment by audrism** [comment]
should work now, please try

**Comment by cloudsreal** [comment]
I connected da4 and installed oscar v2.2.1 too, but i meet the same problem when using python3. How can I address this?
<img width="516" alt="Screenshot 2024-07-12 at 14 29 16" src="https://github.com/user-attachments/assets/fea22019-c9a3-4dbb-9ad7-6ed55047d85f">

**Comment by mahtab-nejati** [comment]
> I connected da4 and installed oscar v2.2.1. <img alt="Screenshot 2024-07-12 at 14 32 11" width="499" src="https://private-user-images.githubusercontent.com/91060689/348149979-1eb478bc-1b3e-484d-9b3a-20ccb7bc0dc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzUxOTQsIm5iZiI6MTcyMzY3NDg5NCwicGF0aCI6Ii85MTA2MDY4OS8zNDgxNDk5NzktMWViNDc4YmMtMWIzZS00ODRkLTliM2EtMjBjY2I3YmMwZGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyMzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MDFhZjYzNzAyN2M0NTc0N2JhY2Q3OTYyNDc1ZjY3OWU2MTgyYTYyMDM4ZTBmNjhlZWQ3YjllZjAzYzdmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bnb4cByt5AD76t7f_WjL0odv20W8OFL1JUyOPwixZX4"> But i met the same problem when using python3. How can I address this? <img alt="Screenshot 2024-07-12 at 14 32 53" width="476" src="https://private-user-images.githubusercontent.com/91060689/348150177-40850b43-107a-4b96-be4d-89682cf7c23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzUxOTQsIm5iZiI6MTcyMzY3NDg5NCwicGF0aCI6Ii85MTA2MDY4OS8zNDgxNTAxNzctNDA4NTBiNDMtMTA3YS00Yjk2LWJlNGQtODk2ODJjZjdjMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIyMzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ODFhNTExMGJjMmYxN2YxNDFhZjc1NTA5YmFhZWYyMmM1YTkxMGZkN2JiZGVkZjZlOTExM2Y4MjlmZjk2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UqkUQ0spwEedkgaZ4kHrK0LmWj4_lx7K636GpNYtZnk">

I'm running into the same issue...

**Comment by audrism** [comment]
can you share your usernames: i'd like to check what is going on

**Comment by audrism** [comment]
I started using two-character versions but it is not compatible

Specifically V3 version is current but having /da5_fast/c2pFullV3.0.tch breaks oscar. 

@hrz6976 can you take look on how to accommodate this: I cant seem to find the right 
place in the code to do it.

**Comment by hrz6976** [comment]
@audrism Okay I'll look into it. Besides, do you think it is viable to change the versioning scheme (e.g. time-based like V2407)? Otherwise we will use up all the letters very soon.

@mahtab-nejati I'd recommend [python-woc](https://github.com/ssc-oscar/python-woc) for new projects: it's fast, python-native, and supports V3 mappings.

**Comment by audrism** [comment]
The package has been updated. 

please do 
```
git pull
```
 in your oscar.py, then build and install
```shell
python3 setup.py build_ext
python3 setup.py install --user
```

Pleas let me know if you still experience issues
